# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-19 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]