# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 23:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AboutUsTitle', models.CharField(blank=True, max_length=50, null=True)),
                ('AboutUsSubcontent', models.TextField(blank=True, null=True)),
                ('AboutUsContent', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeInfoPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HomeInfoTitle', models.CharField(max_length=50)),
                ('HomeInfoSubcontent', models.TextField()),
                ('HomeInfoContent', models.TextField(blank=True, null=True)),
                ('HomeBenefitsSubcontent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HowItWorkPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HowItWorksTitle', models.CharField(blank=True, max_length=50, null=True)),
                ('HowItWorksSubcontent', models.TextField(blank=True, null=True)),
                ('HowItWorksContent', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LendingPolicyPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LendingPolicyTitle', models.CharField(blank=True, max_length=50, null=True)),
                ('LendingPolicySubcontent', models.TextField(blank=True, null=True)),
                ('LendingPolicyContent', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loans_Form_Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typesofloan', models.CharField(choices=[(b'business', b'BUSINESS LOAN'), (b'mortgage', b'MORTGAGE LOAN')], default=b'personal', max_length=50)),
                ('Business_Type', models.CharField(choices=[(b'sole_propietorship', b'Sole Propietorship'), (b'partnership', b'Partnership'), (b'corporation', b'Corporation'), (b's_Corporation', b'S Corporation'), (b'limited_liability_company', b'Limited Liability Company (LLC)')], default=b'', max_length=50)),
                ('Amount_Requested', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Minimum_Amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Reason', models.TextField(default=b'', max_length=1000)),
                ('Business_Name', models.CharField(max_length=50)),
                ('DBA', models.CharField(max_length=50)),
                ('State_Tax_ID_Number', models.IntegerField()),
                ('Federal_Tax_ID_Number', models.IntegerField()),
                ('Business_Contact', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message=b"# must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex=b'^\\+?1?\\d{9,15}$')])),
                ('Business_Address', models.CharField(max_length=50)),
                ('Business_City', models.CharField(max_length=50)),
                ('Business_State', models.CharField(max_length=50)),
                ('Owner_Full_Name', models.CharField(max_length=50)),
                ('Total_Assets', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Net_Worth', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Nature_of_Business', models.CharField(max_length=50)),
                ('Website', models.URLField()),
                ('Business_Inception_Date', models.DateField()),
                ('Annual_Revenue', models.CharField(max_length=50)),
                ('bankruptcy_q', models.IntegerField(choices=[(0, b'No'), (1, b'Yes')], default=0, null=True)),
                ('profit_q', models.IntegerField(choices=[(0, b'No'), (1, b'Yes')], default=0, null=True)),
                ('Business_Zipcode', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message=b"Zip code must be entered in the format: '99999'. Up to 5 digits allowed.", regex=b'^\\+?1?\\d{0,5}$')])),
                ('Full_Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Zip_Code', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message=b"Zip code must be entered in the format: '99999'. Up to 5 digits allowed.", regex=b'^\\+?1?\\d{0,5}$')])),
                ('Date_Of_Birth', models.DateField()),
                ('Email', models.EmailField(max_length=50)),
                ('Credit_Score', models.CharField(choices=[(b'excellent', b'Excellent ( => 720)'), (b'good', b'Good (680 - 719)'), (b'fair', b'Fair (640 - 679)'), (b'poor', b'Poor ( =<639)')], default=b'', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Loans_Form_Mortgage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mortgage_Loan_type', models.CharField(choices=[(b'conventional', b'Conventional'), (b'va', b'VA'), (b'fha', b'FHA'), (b'usda_ruralhousing', b'USDA/Rural Housing'), (b'hard_money', b'Hard Money'), (b'other', b'Other')], default=b'', max_length=50)),
                ('Mortgage_Loan_Purpose', models.CharField(choices=[(b'refinance', b'REFINANCE'), (b'buyhome', b'BUY HOME'), (b'homeequity', b'HOME EQUITY LOAN'), (b'reverse', b'REVERSE MORTGAGE LOAN')], default=b'', max_length=50)),
                ('HIWBU', models.CharField(choices=[(b'primary', b'Primary Home'), (b'secondary', b'Secondary Home'), (b'rental', b'Rental Property')], default=b'', max_length=50)),
                ('m_property_type', models.CharField(choices=[(b'single_family_home', b'Single Family Home'), (b'Townhome', b'Townhome'), (b'condo', b'Condo'), (b'multi_family_dwelling', b'Multi Family Dwelling'), (b'mobile_manufactured_home', b'Mobile/Manufactured Home')], default=b'', max_length=50)),
                ('Payment_Term', models.CharField(choices=[(b'50_Year', b'50 Years'), (b'40_Year', b'40 Years'), (b'30_Years', b'30 Years'), (b'20_Years', b'20 Years'), (b'15_Years', b'15 Years'), (b'10_Years', b'10 Years'), (b'7_Years', b'7 Years'), (b'5_Years', b'5 Years')], default=b'', max_length=50)),
                ('Number_Units', models.CharField(choices=[(b'0', b'0'), (b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4')], default=b'', max_length=50)),
                ('Loan_Amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Amortization_Type', models.CharField(choices=[(b'fixed', b'Fixed Rate'), (b'adjustable', b'Adjustable Rate'), (b'other', b'Other Loan Payment Type')], default=b'', max_length=50)),
                ('Down_Payment_Source', models.CharField(choices=[(b'sale', b'Sale Of Existing'), (b'savings', b'Savings'), (b'equity', b'Equity'), (b'gift', b'Gift')], default=b'', max_length=50)),
                ('property_zipcode', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message=b"Zip code must be entered in the format: '99999'. Up to 5 digits allowed.", regex=b'^\\+?1?\\d{0,5}$')])),
                ('property_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('second_morgage_q', models.IntegerField(choices=[(0, b'No'), (1, b'Yes')], default=0, null=True)),
                ('Full_Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Zip_Code', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message=b"Zip code must be entered in the format: '99999'. Up to 5 digits allowed.", regex=b'^\\+?1?\\d{0,5}$')])),
                ('Date_Of_Birth', models.DateField()),
                ('Work_Phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message=b"# must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex=b'^\\+?1?\\d{9,15}$')])),
                ('Home_Phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message=b"# must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex=b'^\\+?1?\\d{9,15}$')])),
                ('Current_House', models.CharField(choices=[(b'own', b'Own'), (b'rent', b'Rent')], default=b'', max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Years_of_Schooling', models.CharField(choices=[(b'8thgrd', b'8th Grade'), (b'9thgrd', b'9th Grade'), (b'10thgrd', b'10th Grade'), (b'11thgrd', b'11th Grade'), (b'Hight_School_Graduate', b'Hight School Graduate'), (b'1_Yr_College', b'1 Year College'), (b'assotiates_degree', b'Associates Degree'), (b'3_Yr_College', b'3 Year College'), (b'bachelors', b'Bachelors Degree'), (b'jd', b'JD'), (b'md', b'MD'), (b'phd', b'PhD')], default=b'', max_length=50)),
                ('Marrital_Status', models.CharField(choices=[(b'single', b'Single'), (b'married', b'Married')], default=b'', max_length=50)),
                ('Employment_Status', models.CharField(choices=[(b'full_time', b'Full Time'), (b'part_time', b'Part Time'), (b'self_employed', b'Self Employed'), (b'unemployed', b'Unemployed'), (b'other', b'Other')], default=b'', max_length=50)),
                ('Credit_Score', models.CharField(choices=[(b'excellent', b'Excellent ( => 720)'), (b'good', b'Good (680 - 719)'), (b'fair', b'Fair (640 - 679)'), (b'poor', b'Poor ( =<639)')], default=b'', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Loans_Form_Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Personal_Loan_Purpose', models.CharField(choices=[(b'debt_consolidation', b'Debt Consolidation'), (b'credit_card_consolidation', b'Credit Card Consolidation'), (b'home_improvement', b'Home Improvement'), (b'home_buying', b'Home Buying'), (b'majot_purchase', b'Major Purchase'), (b'car_financing', b'Car Financing'), (b'green_loan', b'Green Loan'), (b'business', b'Business'), (b'vacation', b'Vacation'), (b'wedding_expenses', b'Wedding Expenses'), (b'moving_relocation', b'Moving Relocation'), (b'other', b'Other')], default=b'', max_length=50)),
                ('Employment_Status', models.CharField(choices=[(b'full_time', b'Full Time'), (b'part_time', b'Part Time'), (b'self_employed', b'Self Employed'), (b'unemployed', b'Unemployed'), (b'other', b'Other')], default=b'', max_length=50)),
                ('Credit_Score', models.CharField(choices=[(b'excellent', b'Excellent ( => 720)'), (b'good', b'Good (680 - 719)'), (b'fair', b'Fair (640 - 679)'), (b'poor', b'Poor ( =<639)')], default=b'', max_length=50)),
                ('personal_cash_borrow', models.CharField(max_length=50)),
                ('Annual_Tax_Income', models.CharField(max_length=50)),
                ('Full_Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Zip_Code', models.CharField(max_length=50)),
                ('Date_Of_Birth', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RateFeesPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RateFeesTitle', models.CharField(blank=True, max_length=50, null=True)),
                ('RateFeesSubcontent', models.TextField(blank=True, null=True)),
                ('RateFeesContent', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
