# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 15:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_auto_20170406_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans_form_personal',
            name='Contact',
            field=models.CharField(default='s', max_length=15, validators=[django.core.validators.RegexValidator(message=b"# must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex=b'^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loans_form_personal',
            name='Current_House',
            field=models.CharField(choices=[(b'own', b'Own'), (b'rent', b'Rent')], default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='loans_form_personal',
            name='Years_of_Schooling',
            field=models.CharField(choices=[(b'8thgrd', b'8th Grade'), (b'9thgrd', b'9th Grade'), (b'10thgrd', b'10th Grade'), (b'11thgrd', b'11th Grade'), (b'Hight_School_Graduate', b'Hight School Graduate'), (b'1_Yr_College', b'1 Year College'), (b'assotiates_degree', b'Associates Degree'), (b'3_Yr_College', b'3 Year College'), (b'bachelors', b'Bachelors Degree'), (b'jd', b'JD'), (b'md', b'MD'), (b'phd', b'PhD')], default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='loans_form_business',
            name='typesofloan',
            field=models.CharField(choices=[(b'personal', b'PERSONAL LOAN'), (b'business', b'BUSINESS LOAN'), (b'mortgage', b'MORTGAGE LOAN')], default=b'personal', max_length=50),
        ),
        migrations.AlterField(
            model_name='loans_form_personal',
            name='Annual_Tax_Income',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loans_form_personal',
            name='personal_cash_borrow',
            field=models.IntegerField(),
        ),
    ]
