# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_auto_20170407_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUsPosts',
        ),
        migrations.DeleteModel(
            name='HomeInfoPosts',
        ),
        migrations.DeleteModel(
            name='HowItWorkPosts',
        ),
        migrations.DeleteModel(
            name='LendingPolicyPosts',
        ),
        migrations.DeleteModel(
            name='RateFeesPosts',
        ),
    ]
